# Classification thresholds for LFN Project Governance
# This file defines the datapoints and thresholds used in the 'classify' job
# to assign each repository to one of the seven lifecycle phases.

phases:
  spark:
    # Spark: very early or inactive projects
    contributors:
      max: 2          # fewer than 3 unique contributors
    hasRelease: false # no releases present

  incubation:
    # Incubation: some traction but still early
    contributors:
      min: 3          # at least 3 unique contributors
    hasRelease: true  # at least one release
    # no additional velocity requirement

  active:
    # Active Development: high velocity and recent activity
    commits90d:
      min: 20         # at least 20 commits in last 90 days
    silentDays:
      max: 30         # last push within 30 days

  stable:
    # Stable: healthy but less intense than Active
    silentDays:
      min: 31         # no commits in last 30 days
      max: 180        # last push within 180 days

  maintenance_lts:
    # Maintenance / LTS: mature, low activity but maintained
    ageYrs:
      min: 5          # project has existed for at least 5 years
    silentDays:
      min: 181        # no commits in last 180 days
      max: 540        # last push within 540 days (~18 months)
    lastRelDays:
      max: 730        # has released within the last 2 years

  archive:
    # Archive: explicitly marked archived in GitHub
    archived: true

  inaccessible:
    # Inaccessible: private, moved, or error fetching metadata
    reachable: false

# ----------------------------------------------------------------------------
# Additional metrics for future enhancements or deeper insights:
#  These are not yet wired into the workflow logic but can be added as needed.
#
# openSSFScorecard:
#   # Measures security best practices via OSSF Scorecard
#   # Data Points:
#   #   - overallScore: numeric 0–10
#   #   - checkResults: map of individual check statuses
#   # Threshold ideas:
#   #   minScore: 7        # encourage baseline security hygiene
#
# issueActivity:
#   # Tracks issue metrics to gauge community engagement and responsiveness
#   # Data Points:
#   #   - openIssuesCount
#   #   - avgIssueCloseTimeDays
#   # Threshold ideas:
#   #   maxOpenIssues: 20     # upper bound for manageable issue backlog
#   #   maxAvgCloseDays: 14   # ensure timely issue resolution
#
# prResponseTime:
#   # Measures average time to first PR review comment/merge
#   # Data Points:
#   #   - avgTimeToReviewHours
#   #   - avgTimeToMergeDays
#   # Threshold ideas:
#   #   maxReviewHours: 24     # timely feedback loop
#
# securityContactActivity:
#   # Checks that designated security contact has recent activity
#   # Data Points:
#   #   - lastSecurityReviewDays
#   # Threshold ideas:
#   #   maxLastReviewDays: 180  # ensure active security maintenance
#
# tscMembership:
#   # Verifies Technical Steering Committee (TSC) membership recorded
#   # Data Points:
#   #   - tscCount
#   #   - tscRolesFilled (Chair, Secretary, etc.)
#   # Threshold ideas:
#   #   minTSCMembers: 3      # ensure minimal governance oversight
#
# contributionDiversity:
#   # Captures diversity of contributors by domain or company
#   # Data Points:
#   #   - uniqueEmailsDomains
#   # Threshold ideas:
#   #   minDomains: 3         # encourage multi-organizational participation
#
# adoptionMetrics:
#   # Tracks adoption such as downloads, stars, or dependent repos
#   # Data Points:
#   #   - starsCount
#   #   - dependentsCount
#   # Threshold ideas:
#   #   minStars: 50         # gauge community interest
#   #   minDependents: 5     # measure ecosystem uptake
# ----------------------------------------------------------------------------
