name: "Classify Lifecycle Phase"
description: "Evaluate repo metrics and assign LFN lifecycle phase"
inputs:
  repo:
    description: 'GitHub repo in <org>/<name> format'
    required: true
  config_path:
    description: 'Path to classify-config.yml'
    required: true
outputs:
  phase:
    description: "The matched lifecycle phase"
runs:
  using: "node16"
  main: "index.js"
