name: "Classify Lifecycle Phase"
description: "Evaluate repo metrics and assign LFN lifecycle phase"
inputs:
  repo:
    description: "Full repo slug (e.g. org/repo)"
    required: true
  config:
    description: "JSON string of lifecycle classification config"
    required: true
outputs:
  phase:
    description: "The matched lifecycle phase"
runs:
  using: "node16"
  main: "index.js"
